# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  adapter: postgresql
  database: movie_dev
  username: username
  password: password
  pool: 5
  timeout: 5000
